### ISSUE TITLE
atom -> byteslice functions pad with zeros

### ISSUE THREAD

**Issue by matthew-levan** [urbit/ares#108]
Even when an atom has a value that can fit in less than 8 bytes, our `as_bytes()` functions still return a `[u8; 8]`, which isn't usable for some crypto operations (like `++veri:ed:crypto`, for example). 

It looks like we also zero-pad when we construct atoms (see `IndirectAtom::new_raw_mut_bytes()`, etc.). Is this necessary for an allocation reason, like if we assume all allocations are at least one 64-bit word, or something?

**Comment by eamsden** [comment]
Yes our entire memory model is in 64-bit / 8 byte words. In what way is this unusable for crypto jets?

**Comment by matthew-levan** [comment]
I'm not sure I can confidently answer this question, but I do know that
some crypto jets will need the ability to pass urcrypt byteslices which
have a length of less than 8.

**Comment by eamsden** [comment]
you can always re-slice a slice
```
slice[start...end]
```
start inclusive, end exclusive.
