### ISSUE TITLE
Constant nouns in static memory

### ISSUE THREAD

**Issue by eamsden** [urbit/ares#120]
We need a way to put nouns in the executable's static memory, preferably with

- a way to identify static memory as *the most senior* memory for purposes of copying and unifying equality.
- bonus: parse nouns from a string

**Cells**
- Create the struct in the constant function
- point it at the head and tail
- take a static reference to the struct
- cast the static reference to a const pointer
- tag the pointer as a cell

**Direct Atoms**
`D(x)` works fine, no further work needed

**Indirect atoms**
The difficulty here is that byte manipulation in constant context in rust is quite difficult. You can easily e.g. get the length of a byteslice in a `const` function, but creating a new byte array based on that size is a very high bar. So we need some way to lay out the metadata, length, and data into static memory in a constant function.

**Unifying equality**
We must not unify from static memory into the PMA or the NockStack. Thus we need to be able to detect if something is in static memory.

**Copying**
We should not copy from static memory into the PMA or the NockStack. Thus, we need to be able to detect if something is in static memory.

### Hot state
Right now we have a very ugly and verbose encoding of the paths in static hot state, which has to be translated to path nouns when we initialize an interpreter context. We should be able to just write the paths as nouns.

### Pass-through scry gate

Jets for `+mure` and `+mute` (and through them `+mule` and `+mole`) must push a "pass-through" scry gate onto the scry stack. This currently must be constructed for each invocation by allocating on the NockStack:

https://github.com/urbit/ares/blob/23cef0bf409db723c248005dc9087530c460d4c0/rust/ares/src/jets/nock.rs#L158-L176

**Comment by bitemyapp** [comment]
I was nerd-sniped into looking into this. I ended up finding a const generic concat function on Reddit and with some light changes, I was able to adapt it for a byte array use-case.

https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=dc2ef7fb3391a62400c21636775eaaa4

Original post: https://old.reddit.com/r/rust/comments/lz0xsl/concatenating_arrays_at_compiletime_in_rust_151/

I wasn't sure what endianness would be appropriate so I guessed big-endian (network byte order) and figured it could be trivially changed if necessary.

**Comment by eamsden** [comment]
> I was nerd-sniped into looking into this. I ended up finding a const generic concat function on Reddit and with some light changes, I was able to adapt it for a byte array use-case.
> 
> https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=dc2ef7fb3391a62400c21636775eaaa4

Thanks!

> Original post: https://old.reddit.com/r/rust/comments/lz0xsl/concatenating_arrays_at_compiletime_in_rust_151/
> 
> I wasn't sure what endianness would be appropriate so I guessed big-endian (network byte order) and figured it could be trivially changed if necessary.

(Note to implementer: all of Urbit is little-endian so the length endianness will need to be swapped)

**Comment by eamsden** [comment]
I think the engineering required to do this is unlikely to be worth the benefits. Closing.
