### ISSUE TITLE
Ares needs string interpolation on stack

### ISSUE THREAD

**Issue by ashelkovnykov** [urbit/ares#147]
Due to running Ares with `assert_no_alloc` enabled, we are unable to use the default Rust string interpolation because it allocates on the Rust heap. This is currently forcing us to comment out various blocks of code which would be most easily implemented with string interpolation and occasionally causing failures during regular, valid operation due to `eprintln` calls.

We need to overwrite the default string interpolation with a version that uses `NockStack`.

**Comment by eamsden** [comment]
If we implement this we should also implement debug prints as newt flogs, not naked eprintlns

**Comment by eamsden** [comment]
Done as of #221
