### ISSUE TITLE
Use rust crypto for crypto jets

### ISSUE THREAD

**Issue by eamsden** [urbit/ares#156]
In aid of #155, we should see if we can replace Urcrypt with the work of the [Rust Crypto team](https://github.com/RustCrypto).

**Comment by eamsden** [comment]
Tagging for discussion @joemfb @philipcmonk @frodwith @belisarius222 @ashelkovnykov @tacryt-socryp

**Comment by frodwith** [comment]
If this can be accomplished, releasing a new urcrypt with a better dependency story and the same api would be a win.

**Comment by eamsden** [comment]
@matthew-levan has put together #189
