### ISSUE TITLE
2stackz: top-frame copying GC

### ISSUE THREAD

**Issue by eamsden** [urbit/ares#173]
Currently in #143 we hard-reset the stack after each event.. This wipes out our hot and warm states, which are not saved to the snapshot as they contain function pointers. Thus, we have to re-initialize both after every event. Saving the state of the stack and restoring to the saved state suffices to preserve the hot state, which should not change over the course of our execution. However, it is not sufficient to save the warm state, which is reinitialized whenever the cold state changes and thus requires collection of stale entries and HAMT stems.

 Instead we should implement a top-frame copying GC as follows:

- ensure (assert?) that the stack is popped to the top frame, preserving hot and warm states.
- Set a new allocation pointer at the opposite end of the stack arena from the current allocation pointer, causing copies to overwrite the locals area of the current top frame.
- Copy hot and warm state to the allocation arena tracked by the new pointer, using a lightweight stack in memory adjacent to the old pointer.
- Set up new stack and frame pointers at the now-reclaimed end of the stack arena.
- Ensure pointers to hot and warm are updated in interpreter context.

The effect of this is that each event will run with the opposite-orientation frame as top each time. This should be fine, though we should audit for assumptions that "the top is always west." If the top frame has no locals and wasn't using the lightweight stack when we pushed, then this wastes no space. However if for some odd reason we did use locals or the lightweight stack in the top frame, the wasted space is now just part of the allocation area for the new "top" frame, and will be reclaimed when we switch back next time.

@joemfb @frodwith @ashelkovnykov please review this idea.

**Comment by ashelkovnykov** [comment]
I should have read this issue before looking at the PR. After much confusion, @eamsden explained this to me while I was reviewing #175 and I'm on board with it.

As @eamsden points out in the issue, and as @drbeefsupreme noted during the review for #175, we'll need to either audit the code for "top is west frame" assumptions, and we should keep this change in mind during future debugging efforts, when and if memory errors appear. (Maybe make a "likely candidates" playbook to document potential bug-causing PRs?).

**Comment by eamsden** [comment]
This was fixed in #178 after being merged and reverted in #175 and #177
