### ISSUE TITLE
Jet testing workflow

### ISSUE THREAD

**Issue by h33p** [urbit/ares#49]
It would make sense to be able to verify jet behavior against trusted implementation (i.e. vere). This could improve test cases and assurance that said test cases are correct. Ideally there would be a tool to supply test inputs and generate unit tests with expected outputs returned by vere.

**Comment by eamsden** [comment]
Vere actually has a mode where one runs both the jet and the matching nock, and bails on a mismatch. We should probably have, at least, something similar.

**Comment by h33p** [comment]
I suppose a prerequisite for that would be to actually match jets to specific nock?

**Comment by eamsden** [comment]
You have to do that to run a jet and we already do it, sort of, with the `%sham` hint. But it's just, anytime you'd run a jet in place of nock, instead run both and bail on a mismatch.

**Comment by philipcmonk** [comment]
This test mode actually exists, if you add the test to this function: https://github.com/urbit/ares/blob/69a0cca9830bc9a05ee66cce049b5607e6e25793/rust/ares/src/jets.rs#L72
