### ISSUE TITLE
"Packed Cell" encoding

### ISSUE THREAD

**Issue by eamsden** [urbit/ares#5]
The current cell encoding is rather heavyweight in its memory use. Each cell consists of a tagged 8-byte pointer to a 24-byte struct, consisting of:

- 8 bytes of metadata (for alignment, only 4 bytes are needed for mugs)
- 8 bytes to store the head of the cell
- 8 bytes to store the tail of the cell

All structure in nouns is encoded with cells, so such a heavyweight encoding is likely to create memory pressure. There are 2 major inefficiencies:
- 4 bytes are wasted for alignment purposes to store the metadata.
- 8 bytes each are used to store a pointer to something which, given the use of a bump allocator and copying collector, is likely very nearly adjacent.

It may be possible to produce a "packed" representation of a cell which need not be a tagged pointer, but rather packs the mug and offsets from itself to its children into a 64 bit word. Such a representation could not be directly loaded into a register or local variable, as the offset information would then be meaningless. It could however be dynamically converted, since we use accessor methods for cells already. Probably this form would never be created by user code calling some variant of `Cell::new()`, but would instead be created by the copier after checking the constraints. Since the copier is also responsible for laying out a copied noun in memory, combining this representation with a breadth-first traversal for copying nouns could result in nearly 3x savings in cell memory allocations in the best case.

**Comment by joemfb** [comment]
It'd be great to experiment with this. I'm not sure if it'd be worth including the mug -- that's a lot of bits. Another possibility is to include head/tail atoms directly where possible -- non-null `+unit`s (and maybe some tagged unions) could effectively be encoding with tagged pointers.

**Comment by eamsden** [comment]
> I'm not sure if it'd be worth including the mug 
It's necessary because otherwise you have to copy everything below the cell back to the current frame to mug it, and the mug cache won't get propagated back to the original copy.
