### ISSUE TITLE
improve tool chain consistency across local/CI builds

### ISSUE THREAD

**Issue by barter-simsum** [urbit/ares#56]
- Need to specify versions for dependencies
- The CI isn't currently using nix -- should it?
- With the cc crate added in #53, we're building with gcc on linux and clang on macos. We should force clang across platforms. The cc crate uses whatever compiler is specified by the `CC` environment variable

**Comment by eamsden** [comment]
Having CI use nix is one option, using rustup is another: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

Whatever we are doing should fix the environment variables for the `cc` package to use clang.

I don't want to use nix to build Ares but using nix to set up the build environment might be acceptable.

**Comment by ashelkovnykov** [comment]
I vote for `rustup` toolchains

**Comment by eamsden** [comment]
https://github.com/marketplace/actions/nix-shell then builds will run in the same Nix shell that we use as a local dev environment, but Ares will not be built with nix.

**Comment by matthew-levan** [comment]
FWIW I don't use `nix` as my local development environment.

**Comment by eamsden** [comment]
This is done: local developers and CI build in the same Nix shell, and the nix and rust builds are properly cached in CI
