### ISSUE TITLE
MacOS CI?

### ISSUE THREAD

**Issue by eamsden** [urbit/ares#57]
https://github.com/urbit/ares/pull/53#issuecomment-1553743862

Dual-platform Ares is nice but not necessary for the initial sprint. IMO it makes sense to get it working on Linux, doing our best not to make MacOS harder for ourselves, and then do a separate block of work after initial release to add a MacOS target. If this is the case then MacOS CI is just getting in the way for now.

Requesting comment from active devs, plus (not mutually exclusively)
@philipcmonk @joemfb @belisarius222 @tacryt-socryp

**Comment by ashelkovnykov** [comment]
I agree

**Comment by barter-simsum** [comment]
agree

**Comment by philipcmonk** [comment]
I also agree. Nothing we're doing is impossible on a mac, so we shouldn't
slow ourselves down with it, unless we have a particular reason to worry
(eg we want to pull in some library that does work on mac)

**Comment by tacryt-socryp** [comment]
rationale makes sense, press the gas

**Comment by eamsden** [comment]
@ashelkovnykov when you make the CI changes to enforce no warnings can you also disable the MacOS target?

**Comment by ashelkovnykov** [comment]
@eamsden Yup, pre-assigned to myself for this reason

**Comment by ashelkovnykov** [comment]
Resolved by #58
