### ISSUE TITLE
+cut jet tries to allocate size 0 indirect atom

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/ares#69]
`(cut [3 [0 0] 0])` causes Ares to crash:

@philipcmonk wrote this I believe?

```
thread '<unnamed>' panicked at 'assertion failed: size > 0', external/crate_index__ares-0.1.0/src/noun.rs:314:9
stack backtrace:
0: _rust_begin_unwind
1: core::panicking::panic_fmt
2: core::panicking::panic
3: ares::noun::IndirectAtom::new_raw_mut
4: ares::noun::IndirectAtom::new_raw_mut_zeroed
5: ares::noun::IndirectAtom::new_raw_mut_bitslice
6: ares::jets::math::jet_cut
7: ares::interpreter::match_pre_hint
8: ares::interpreter::interpret::{{closure}}
...
```

**Comment by eamsden** [comment]
The cut jet works by allocating an indirect atom sized by the block size and step to receive the result, and then normalizing it after the result is copied in. This fails in the case where the difference between the steps is 0:
https://github.com/urbit/ares/blob/995f64da8c127b7b8c54ba427277cbbd2e531711/rust/ares/src/jets/math.rs#L548

The simplest fix is probably to check if the step difference is 0 and preemptively return 0 as a direct atom. @drbeefsupreme

**Comment by eamsden** [comment]
Whoever fixes this, please also add a regression test in the test suite at the end of jets/math.rs
