### ISSUE TITLE
`jam` issue in `SIGINT` branch

### ISSUE THREAD

**Issue by ashelkovnykov** [urbit/ares#93]
I'm seeing non-determinism in `jam` on the [ctrlc branch](https://github.com/urbit/ares/tree/ctrlc) which contains my `SIGINT` work. The code is hooked up and working correctly, but roughly 1/4 interrupts cause the King to fail with an error during `cue` (`_cs_cue_xeno` via `u3s_cue_xeno_with` via `_lord_on_plea`).

This can be tested on the above-linked branch by compiling `toddler.hoon` into a pill, starting it with the Ares code from that same branch, waiting until initial boot completes, and then pressing any key to start a long-running event (~2 seconds) and interrupting it with `ctrl-C`.

**Comment by ashelkovnykov** [comment]
More context: the `_cs_cue_xeno` returns `~` (meaning failed cue) and then fails on `assert(u3_none != a)` in `u3r_cell` when `_lord_on_plea` attempts to treat it as a cell to read the tag and datum from it

**Comment by eamsden** [comment]
@ashelkovnykov do you believe this is also fixed by #100 / #102 ?

**Comment by ashelkovnykov** [comment]
Fixed by #98
