### ISSUE TITLE
no_alloc debug flag

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/ares#97]
When `assert_no_alloc()` fires, it doesn't tell you what caused it. It would be good to have a debug flag that turns it off to find out why, instead of commenting it out like I currently do. (maybe this is already an option somehow with the crate)

**Comment by drbeefsupreme** [comment]
On second thought, my bug just happens to crash Ares if it isn't caught by `assert_no_alloc()` so just turning it off wouldn't be super userful. I guess I mostly would like to know what line it happens at, but maybe the answer is just "use `gdb`".

**Comment by eamsden** [comment]
if it is trying to panic and crashing because it allocates during panic, you can turn on the "warn_debug" feature temporarily for the assert_no_alloc crate.

```diff
-assert_no_alloc = "1.1.2"
+assert_no_alloc = { version = "1.1.2", features = [ "warn_debug" ] }
```
